name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      # Remove cached files to prevent the Rollup error
      - name: Clear npm cache
        run: npm cache clean --force
      
      # Clean install with specific fix for Rollup issue
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-save
          npm install @rollup/rollup-linux-x64-gnu --no-save
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build with Astro
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
